# Service Registry service
--- 
apiVersion: v1
kind: Service
metadata:
  name: eventhandler
spec:
  ports:
  - port: 8455
  selector:
    type: optional
    app: eh
  clusterIP: None

# Service Registry deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eh-deployment
  labels:
    type: optional-service
spec: # Deployment scpecifications
  replicas: 1
  selector:
    matchLabels:
      type: optional
      app: eh
  template:
    metadata:
      labels:
        type: optional
        app: eh
    spec: # Docker Network
      containers: 
      - name: eventhandler
        image: alexmedela/eventhandler:4.4.1
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        ports:
        - containerPort: 8455
        volumeMounts:
        - name: eventhandler-volume
          mountPath: /eventhandler/application.properties
          subPath: application.properties
        - name: eh-cert-volume
          mountPath: /eventhandler/eventhandler.p12
          subPath: eventhandler.p12
        - name: truststore-volume
          mountPath: /serviceregistry/truststore.p12
          subPath: truststore.p12
      volumes: # Docker Network Volumes
        - name: eventhandler-volume
          configMap:
            name: properties
            items:
            - key: eventhandler.properties
              path: application.properties
        - name: eh-cert-volume
          configMap:
            name: certs
            items:
            - key: eventhandler.p12
              path: eventhandler.p12
        - name: truststore-volume
          configMap:
            name: certs
            items:
            - key: testcloud1.truststore.p12
              path: truststore.p12
