apiVersion: v1
data:
  authorization.properties: "############################################\n###       APPLICATION
    PARAMETERS         ###\n############################################\n\n# Database
    connection (mandatory)\n# Change the server timezone if neccessary\nspring.datasource.url=jdbc:mysql://mysql-mariadb-galera:3306/arrowhead?serverTimezone=Europe/Budapest
    \ \nspring.datasource.username=authorization\nspring.datasource.password=hqZFUkuHxhekio3\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\n\nspring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect\n#
    use true only for debugging\nspring.jpa.show-sql=false  \nspring.jpa.properties.hibernate.format_sql=true\nspring.jpa.hibernate.ddl-auto=none\n\n#
    Authorization web-server parameters\nserver.address=0.0.0.0\nserver.port=8445\ndomain.name=authorization\ndomain.port=8445\n\n############################################\n###
    \      CUSTOM PARAMETERS              ###\n############################################\n\n#
    Name of the core system\ncore_system_name=AUTHORIZATION\n\n# Show all request/response
    in debug log\nlog_all_request_and_response=false\n\n# Service Registry web-server
    parameters (to register the Authorization services)\nsr_address=serviceregistry\nsr_port=8443\n\n#
    Interface names has to follow this format <PROTOCOL>-<SECURITY>-<FORMAT>, where
    security can be SECURE or INSECURE and protocol and format must be a sequence
    of letters, numbers and underscore.\n# A regexp checker will verify that. If this
    setting is set to true then the PROTOCOL and FORMAT must come from a predefined
    set.\nuse_strict_service_intf_name_verifier=false\n\n# Event handler core system
    is present\neventhandler_is_present=false\n\n############################################\n###
    \          SECURE MODE                ###\n############################################\n\n#
    configure secure mode\n\n# Set this to false to disable https mode\nserver.ssl.enabled=true\n\nserver.ssl.key-store-type=PKCS12\nserver.ssl.key-store=classpath:certificates/authorization.p12\nserver.ssl.key-store-password=123456\nserver.ssl.key-alias=authorization\nserver.ssl.key-password=123456\nserver.ssl.client-auth=need\nserver.ssl.trust-store-type=PKCS12\nserver.ssl.trust-store=classpath:certificates/truststore.p12\nserver.ssl.trust-store-password=123456\n\n#
    If true, http client does not check whether the hostname is match one of the server's
    SAN in its certificate\n# Just for testing, DO NOT USE this feature in production
    environment \ndisable.hostname.verifier=true"
  eventhandler.properties: "############################################\r\n###       APPLICATION
    PARAMETERS         ###\r\n############################################\r\n\r\n#
    Database connection (mandatory)\r\n# Change the server timezone if neccessary\r\nspring.datasource.url=jdbc:mysql://mysql-mariadb-galera:3306/arrowhead?serverTimezone=Europe/Budapest
    \ \r\nspring.datasource.username=event_handler\r\nspring.datasource.password=gRLjXbqu9YwYhfK\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\n\r\nspring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect\r\n#
    use true only for debugging\r\nspring.jpa.show-sql=false  \r\nspring.jpa.properties.hibernate.format_sql=true\r\nspring.jpa.hibernate.ddl-auto=none\r\n\r\n#
    Event handler web-server parameters\r\nserver.address=0.0.0.0\r\nserver.port=8455\r\ndomain.name=eventhandler\r\ndomain.port=8455\r\n\r\n############################################\r\n###
    \      CUSTOM PARAMETERS              ###\r\n############################################\r\n\r\n#
    Name of the core system\r\ncore_system_name=EVENTHANDLER \r\n\r\n# Show all request/response
    in debug log\r\nlog_all_request_and_response=false\r\n\r\n# Service Registry web-server
    parameters (to register the Event Handler services)\r\nsr_address=serviceregistry\r\nsr_port=8443\r\n\r\n#
    TimeStamp tolerance: clients can publish and subscribe(starttime/endtime) events
    with timestamps X number of secounds before or after the current time\r\ntime_stamp_tolerance_seconds=120\r\n\r\n#
    Removing old Subscriptions from the database based on the endDate field (true/false)\r\nevent_handler_ttl_scheduled=false\r\n\r\n#
    DB check interval in minutes, if \"event_handler_ttl_scheduled\" is true\r\nevent_handler_ttl_interval=60\r\n\r\n#
    Maximum number of subscribers on an express publish chanel\r\n# if there are more
    valid subscribers for and event there is going to be a resource creation overhead\r\nevent_handler_max_express_subscribers=10\r\n\r\n#
    Maximum number of retries to connect authorization core system at startup before
    fail\r\nevent_handler_max_retry_connect_auth=3\r\n\r\n# Seconds to wait between
    event_handler_retry_connect_auth\r\nevent_handler_retry_connect_auth_interval_sec=10\r\n\r\n############################################\r\n###
    \          SECURE MODE                ###\r\n############################################\r\n\r\n#
    configure secure mode\r\n\r\n# Set this to false to disable https mode\r\nserver.ssl.enabled=true\r\n\r\nserver.ssl.key-store-type=PKCS12\r\nserver.ssl.key-store=classpath:certificates/eventhandler.p12\r\nserver.ssl.key-store-password=123456\r\nserver.ssl.key-alias=eventhandler\r\nserver.ssl.key-password=123456\r\nserver.ssl.client-auth=need\r\nserver.ssl.trust-store-type=PKCS12\r\nserver.ssl.trust-store=classpath:certificates/truststore.p12\r\nserver.ssl.trust-store-password=123456\r\n\r\n#If
    true, http client does not check whether the hostname is match one of the server's
    SAN in its certificate\r\n#Just for testing, DO NOT USE this feature in production
    environment \r\ndisable.hostname.verifier=true\r\n"
  gatekeeper.properties: "############################################\n###       APPLICATION
    PARAMETERS         ###\n############################################\n\n# Database
    connection (mandatory)\n# Change the server timezone if neccessary\nspring.datasource.url=jdbc:mysql://mysql-mariadb-galera:3306/arrowhead?serverTimezone=Europe/Budapest
    \ \nspring.datasource.username=gatekeeper\nspring.datasource.password=fbJKYzKhU5t8QtT\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\n\nspring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect\n#
    use true only for debugging\nspring.jpa.show-sql=false  \nspring.jpa.properties.hibernate.format_sql=true\nspring.jpa.hibernate.ddl-auto=none\n\n#
    Parameters of Gatekeeper web-server\nserver.address=0.0.0.0\nserver.port=8449\ndomain.name=gatekeeper\ndomain.port=8449\n\n############################################\n###
    \      CUSTOM PARAMETERS              ###\n############################################\n\n#
    Name of the core system\ncore_system_name=GATEKEEPER \n\n# Show all request/response
    in debug log\nlog_all_request_and_response=false\n\n# Service Registry web-server
    parameters (to register the Gatekeeper services)\nsr_address=serviceregistry\nsr_port=8443\n\n#
    Inter-Cloud communication timeout in milliseconds\ntimeout=30000\n\n# If true,
    operaional gateway must be present\ngateway_is_present=true\n\n# Using the Gateway
    module is mandatory or not during Inter-Cloud orchestration (true/false)\ngateway_is_mandatory=true\n\n############################################\n###
    \          SECURE MODE                ###\n############################################\n\n#
    configure secure mode\n\n# Set this to false to disable https mode\nserver.ssl.enabled=true\n\nserver.ssl.key-store-type=PKCS12\nserver.ssl.key-store=classpath:certificates/gatekeeper.p12\nserver.ssl.key-store-password=123456\nserver.ssl.key-alias=gatekeeper\nserver.ssl.key-password=123456\nserver.ssl.client-auth=need\nserver.ssl.trust-store-type=PKCS12\nserver.ssl.trust-store=classpath:certificates/truststore.p12\nserver.ssl.trust-store-password=123456\n\n#If
    true, http client does not check whether the hostname is match one of the server's
    SAN in its certificate\n#Just for testing, DO NOT USE this feature in production
    environment \ndisable.hostname.verifier=true\n\nhttp.client.socket.timeout=120000\nhttp.client.connection.timeout=120000\nhttp.client.connection.manager.timeout=120000\n"
  gateway.properties: "############################################\n###       APPLICATION
    PARAMETERS         ###\n############################################\n\n# Database
    connection (mandatory)\n# Change the server timezone if neccessary\nspring.datasource.url=jdbc:mysql://mysql-mariadb-galera:3306/arrowhead?serverTimezone=Europe/Budapest
    \ \nspring.datasource.username=gateway\nspring.datasource.password=LfiSM9DpGfDEP5g\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\n\nspring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect\n#
    use true only for debugging\nspring.jpa.show-sql=false  \nspring.jpa.properties.hibernate.format_sql=true\nspring.jpa.hibernate.ddl-auto=none\n\n#
    Parameters of Gateway web-server\nserver.address=0.0.0.0\nserver.port=8453\ndomain.name=gateway\ndomain.port=8453\n\n############################################\n###
    \      CUSTOM PARAMETERS              ###\n############################################\n\n#
    Name of the core system\ncore_system_name=GATEWAY \n\n# Show all request/response
    in debug log\nlog_all_request_and_response=false\n\n# Service Registry web-server
    parameters (to register the Gateway services)\nsr_address=serviceregistry\nsr_port=8443\n\n#
    Port range for socket openings (to facilitate inter-cloud communication between
    consumer and provider systems)\nmin_port=8000\nmax_port=8100\nprovider_side_max_request_per_socket=50\n\n############################################\n###
    \          SECURE MODE                ###\n############################################\n\n#
    configure secure mode\n\n# Set this to false to disable https mode\nserver.ssl.enabled=true\n\nserver.ssl.key-store-type=PKCS12\nserver.ssl.key-store=classpath:certificates/gateway.p12\nserver.ssl.key-store-password=123456\nserver.ssl.key-alias=gateway\nserver.ssl.key-password=123456\nserver.ssl.client-auth=need\nserver.ssl.trust-store-type=PKCS12\nserver.ssl.trust-store=classpath:certificates/truststore.p12\nserver.ssl.trust-store-password=123456\n\n#If
    true, http client does not check whether the hostname is match one of the server's
    SAN in its certificate\n#Just for testing, DO NOT USE this feature in production
    environment \ndisable.hostname.verifier=true\n"
  orchestrator.properties: "############################################\r\n###       APPLICATION
    PARAMETERS         ###\r\n############################################\r\n\r\n#
    Database connection (mandatory)\r\n# Change the server timezone if neccessary\r\nspring.datasource.url=jdbc:mysql://mysql-mariadb-galera:3306/arrowhead?serverTimezone=Europe/Budapest
    \ \r\nspring.datasource.username=orchestrator\r\nspring.datasource.password=KbgD2mTr8DQ4vtc\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\n\r\nspring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect\r\n#
    use true only for debugging\r\nspring.jpa.show-sql=false\r\nspring.jpa.properties.hibernate.format_sql=true\r\nspring.jpa.hibernate.ddl-auto=none\r\n\r\n#
    Orchestrator web-server parameters\r\nserver.address=0.0.0.0\r\nserver.port=8441\r\ndomain.name=orchestrator\r\ndomain.port=8441\r\n\r\n############################################\r\n###
    \      CUSTOM PARAMETERS              ###\r\n############################################\r\n\r\n#
    Name of the core system\r\ncore_system_name=ORCHESTRATOR\r\n \r\n# Show all request/response
    in debug log\r\nlog_all_request_and_response=false\r\n\r\n# Service Registry web-server
    parameters (to register the Orchestrator services)\r\nsr_address=serviceregistry\r\nsr_port=8443\r\n\r\n#If
    true, orchestrator will use flexible store in case of store-orchestration\r\nuse_flexible_store=false\r\n\r\n#
    If true, service definitions has to follow these rules: They only contains letters
    (english alphabet), numbers and dash (-), and have to start with a letter (also
    cannot end with dash)\r\nuse_strict_service_definition_verifier=true\r\n\r\n#If
    true, operational gatekeeper must be present\r\ngatekeeper_is_present=false\r\n\r\n#If
    true, orchestrator will use QoS verification and reservation (if clients using
    this feature)\r\n#Due to licensing issues, QoS Manager is unavailable for now,
    keep this flag on false.\r\nenable_qos=false\r\n\r\n#How frequently the database
    should be checked for expired reservations, in seconds\r\nqos_reservation_check_interval=120\r\n\r\n#How
    long a cached ping measurement can use without refreshing using the Qos Monitor's
    webservice, in seconds\r\nqos_ping_measurement_cache_threshold=600\r\n\r\n# Interface
    names has to follow this format <PROTOCOL>-<SECURITY>-<FORMAT>, where security
    can be SECURE or INSECURE and protocol and format must be a sequence of letters,
    numbers and underscore.\r\n# A regexp checker will verify that. If this setting
    is set to true then the PROTOCOL and FORMAT must come from a predefined set.\r\nuse_strict_service_intf_name_verifier=false\r\n\r\n############################################\r\n###
    \          SECURE MODE                ###\r\n############################################\r\n\r\n#
    configure secure mode\r\n\r\n# Set this to false to disable https mode\r\nserver.ssl.enabled=true\r\n\r\nserver.ssl.key-store-type=PKCS12\r\nserver.ssl.key-store=classpath:certificates/orchestrator.p12\r\nserver.ssl.key-store-password=123456\r\nserver.ssl.key-alias=orchestrator\r\nserver.ssl.key-password=123456\r\nserver.ssl.client-auth=need\r\nserver.ssl.trust-store-type=PKCS12\r\nserver.ssl.trust-store=classpath:certificates/truststore.p12\r\nserver.ssl.trust-store-password=123456\r\n\r\n#If
    true, http client does not check whether the hostname is match one of the server's
    SAN in its certificate\r\n#Just for testing, DO NOT USE this feature in production
    environment \r\ndisable.hostname.verifier=true"
  serviceregistry.properties: "############################################\n###       APPLICATION
    PARAMETERS         ###\n############################################\n\n# Database
    connection (mandatory)\n# Change the server timezone if neccessary\nspring.datasource.url=jdbc:mysql://mysql-mariadb-galera:3306/arrowhead?serverTimezone=Europe/Budapest
    \ \nspring.datasource.username=service_registry\nspring.datasource.password=ZzNNpxrbZGVvfJ8\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\n\nspring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect\n#
    use true only for debugging\nspring.jpa.show-sql=false  \nspring.jpa.properties.hibernate.format_sql=true\nspring.jpa.hibernate.ddl-auto=none\n\n#
    Service Registry web-server parameters\nserver.address=0.0.0.0\nserver.port=8443\ndomain.name=serviceregistry\ndomain.port=8443\n\n############################################\n###
    \      CUSTOM PARAMETERS              ###\n############################################\n\n#
    Name of the core system\ncore_system_name=SERVICEREGISTRY \n\n# Show all request/response
    in debug log\nlog_all_request_and_response=false\n\n# Service Registry has an
    optional feature to ping service providers in a fixed time interval,\n# and remove
    service offerings where the service provider was not available\n# use this feature
    (true/false)\nping_scheduled=false\n# how much time the Service Registry should
    wait for the ping response (in milliseconds)\nping_timeout=5000\n# how frequently
    should the ping happen, in minutes\nping_interval=60\n\n# Service Registry has
    an optional feature to automatically remove service offerings, where the endOfValidity\n#
    timestamp field is in the past, meaning the offering expired\n# use this feature
    (true/false)\nttl_scheduled=false\n# how frequently the database should be checked
    for expired services, in minutes\nttl_interval=10\n\n# Interface names has to
    follow this format <PROTOCOL>-<SECURITY>-<FORMAT>, where security can be SECURE
    or INSECURE and protocol and format must be a sequence of letters, numbers and
    underscore.\n# A regexp checker will verify that. If this setting is set to true
    then the PROTOCOL and FORMAT must come from a predefined set.\nuse_strict_service_intf_name_verifier=false\n\n#
    If true, service definitions has to follow these rules: They only contains letters
    (english alphabet), numbers and dash (-), and have to start with a letter (also
    cannot end with dash)\nuse_strict_service_definition_verifier=true\n\n# If true,
    address detection from HttpServletRequest will be performed at the time of systems
    and service registration/unregistration\nuse_network_address_detector=false\n#
    Comma separated list representing the possible proxy servers like load-balancer
    etc... before ServiceRegistry\nfilter_proxy_addresses=\n\n# If true, the registration
    of systems with self-addressing IPv4, IPv6 and no-type addresses are allowed.\n#
    In case of self-addressing addresses the IP packets cannot be directed from one
    device to another.\nallow_self_addressing=true\n\n# If true, the registration
    of systems with non-routable IPv4 and IPv6 addresses are allowed.\n# In case of
    \ non-routable addresses the IP packets cannot be directed from one network to
    another.\nallow_non_routable_addressing=true\n\n############################################\n###
    \          SECURE MODE                ###\n############################################\n\n#
    configure secure mode\n\n# Set this to false to disable https mode\nserver.ssl.enabled=true\n\nserver.ssl.key-store-type=PKCS12\nserver.ssl.key-store=classpath:certificates/serviceregistry.p12\nserver.ssl.key-store-password=123456\nserver.ssl.key-alias=serviceregistry\nserver.ssl.key-password=123456\nserver.ssl.client-auth=need\nserver.ssl.trust-store-type=PKCS12\nserver.ssl.trust-store=classpath:certificates/truststore.p12\nserver.ssl.trust-store-password=123456\n\n#If
    true, http client does not check whether the hostname is match one of the server's
    SAN in its certificate\n#Just for testing, DO NOT USE this feature in production
    environment \ndisable.hostname.verifier=true\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-28T11:13:18Z"
  name: properties
  namespace: default
  resourceVersion: "738"
  uid: d49530db-1ba3-4c0e-931e-7dce9e05186b
